# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: plexDIA
long_title: Multiplexed data-independent acquisition: plexDIA
description: Sensitive, accurate and high-throughput proteomics by multiplexed data-independent acquisition (plexDIA). plexDIA for increasing proteomics throughput | Slavov Laboratory and single-cell proteomics center
baseurl: ~ # the subpath of your site, e.g. /blog
url: https://plexDIA.slavovlab.net # the base hostname & protocol for your site

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
#aux_links:
#  "bioRxiv Preprint":
#    - "https://www.biorxiv.org/content/10.1101/512152v1"
#  "GitHub Repository":
#    - "https://github.com/SlavovLab/SCoPE2"

aux_links:
  "plexDIA Preprint":
    - "https://doi.org/10.1101/2021.11.03.467007"
  "Slavov Lab":
    - "https://slavovlab.net"
  "SCP Center":
    - "https://center.single-cell.net"



github_link: https://github.com/SlavovLab/plexDIA
preprint_link: https://doi.org/10.1101/2021.11.03.467007


# Color scheme currently only supports "dark" or nil (default)
color_scheme: blue

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-4005755-3


plugins:
  - jekyll-seo-tag

theme: jekyll-theme-slate
